# -*- coding: utf-8 -*-
"""app_TCM.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJWVfjSj5I-wK474ZfG83HN2mb5Gvdmf
"""

# Traditional Chinese Medicine Web App MVP (Streamlit)
import streamlit as st
import pandas as pd
from PIL import Image
import os
import uuid
from datetime import datetime

# ---- SETUP ----
st.set_page_config(page_title="TCM Health App", layout="wide")
if "submissions" not in st.session_state:
    st.session_state.submissions = []

# ---- NAVIGATION ----
pages = ["Educational Content", "Tongue Health Check", "About & Disclaimer"]
page = st.sidebar.radio("Navigate", pages)

# ---- 1. EDUCATIONAL CONTENT ----
if page == "Educational Content":
    st.title("🌿 Traditional Chinese Medicine (TCM) Basics")
    st.header("What is TCM?")
    st.write("""
        Traditional Chinese Medicine is a holistic approach to health that includes practices like acupuncture,
        herbal medicine, massage (Tui Na), exercise (Qi Gong), and dietary therapy. It is based on concepts such as:
        - **Yin & Yang**: Balance between opposite but complementary forces
        - **Qi (Chi)**: Vital energy flowing through the body
        - **Five Elements**: Wood, Fire, Earth, Metal, Water—linked to organs and emotions

        TCM often contrasts with **Western medicine**, which tends to focus on pathology, lab diagnostics, and medications.
    """)

    st.subheader("Sources")
    st.markdown("- [WHO on TCM](https://www.who.int/health-topics/traditional-complementary-and-integrative-medicine)")
    st.markdown("- [PubMed on TCM Research](https://pubmed.ncbi.nlm.nih.gov/?term=traditional+chinese+medicine)")

# ---- 2. TONGUE HEALTH CHECK ----
elif page == "Tongue Health Check":
    st.title("👅 Tongue Diagnosis Tool")

    st.subheader("Step 1: Upload Your Tongue Image")
    uploaded_img = st.file_uploader("Upload a clear image of your tongue", type=["jpg", "jpeg", "png"])

    if uploaded_img:
        img = Image.open(uploaded_img)
        st.image(img, caption="Uploaded Tongue Image", use_column_width=True)

    st.subheader("Step 2: Describe Your Current Symptoms")
    symptoms = st.text_area("Describe what you’re feeling physically or emotionally (e.g. tiredness, stress, stomach ache)")

    st.subheader("Step 3: Consent & Disclaimer")
    consent = st.checkbox("I consent to the use of my image and data for future research and model training.")

    st.info("This app does not provide a medical diagnosis. It is for educational and research purposes only.")

    st.subheader("Step 4: Submit for Analysis")
    if st.button("🔍 Analyze My Tongue"):
        if uploaded_img and consent:
            submission_id = str(uuid.uuid4())
            timestamp = datetime.utcnow().isoformat()

            # Save image locally (or later to Firebase/S3)
            os.makedirs("submissions", exist_ok=True)
            img.save(f"submissions/{submission_id}.png")

            # Save metadata (as placeholder CSV)
            data_row = {
                "id": submission_id,
                "timestamp": timestamp,
                "symptoms": symptoms,
                "tongue_image_path": f"submissions/{submission_id}.png",
                "prediction_TCM": "Qi Deficiency (placeholder)",
                "prediction_Western": "Possible Fatigue/Anemia (placeholder)",
                "user_feedback": ""
            }
            st.session_state.submissions.append(data_row)
            st.success("Image submitted successfully! Scroll down for prediction.")

            # Display placeholder predictions
            st.subheader("Predictions")
            st.markdown("- **TCM Insight**: Qi Deficiency (based on image features)")
            st.markdown("- **Western Equivalent**: Possible signs of fatigue or low hemoglobin")

            # Feedback
            st.subheader("How accurate was this?")
            feedback = st.text_input("Your feedback or correction (optional)")
            if feedback:
                st.session_state.submissions[-1]["user_feedback"] = feedback
                st.success("Thanks! Your feedback helps improve our model.")
        else:
            st.error("Please upload an image and provide consent.")

# ---- 3. ABOUT & DISCLAIMER ----
elif page == "About & Disclaimer":
    st.title("📜 About This App")
    st.write("""
        This application is a prototype designed to:
        - Educate the public on Traditional Chinese Medicine
        - Demonstrate how tongue analysis can indicate overall health
        - Begin building a dataset for research into health diagnostics via images

        ⚠️ **Disclaimer**: This app does NOT replace professional medical advice.
        Your image and responses will be stored securely and anonymously, used only for improving predictive capabilities.
    """)